"""One-command developer bootstrap.

What this script does:
  1. Verifies Docker + docker compose v2 are installed.
  2. Generates a strong dev secret + dev API key, writing them to ``.env``.
  3. Optionally pulls or builds the api + web images.
  4. Brings the stack up with ``docker compose -f deploy/docker-compose.dev.yml up -d``.
  5. Waits for /health and prints the live URLs.

Run from the repo root:

    python scripts/bootstrap_dev.py

Re-running is idempotent: an existing ``.env`` is preserved unless ``--rotate-keys``
is passed. The API key is hashed inside the API on startup; the raw value lives
only in ``.env`` so you can paste it into the web portal env when needed.
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import string
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
WEB_ENV_FILE = REPO_ROOT / "packages" / "web" / ".env.local"
COMPOSE_FILE = REPO_ROOT / "deploy" / "docker-compose.dev.yml"

ALPHABET = string.ascii_letters + string.digits


def _gen(n: int) -> str:
    return "".join(secrets.choice(ALPHABET) for _ in range(n))


def _gen_api_key(env: str = "dev") -> str:
    """Match the format ``pps_<env>_<32 base62>`` used by api_key.py."""
    return f"pps_{env}_{_gen(32)}"


def _need(cmd: str) -> str:
    path = shutil.which(cmd)
    if path is None:
        sys.exit(f"error: '{cmd}' is not on PATH. Install it before running bootstrap.")
    return path


def _check_docker_compose() -> None:
    docker = _need("docker")
    try:
        subprocess.run(
            [docker, "compose", "version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError:
        sys.exit("error: 'docker compose' v2 plugin is required (not the legacy 'docker-compose').")


def _read_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_env(path: Path, values: dict[str, str], header: str) -> None:
    body = [
        "# " + header.replace("\n", "\n# "),
        "# Generated by scripts/bootstrap_dev.py.",
        "",
    ]
    for k, v in values.items():
        body.append(f"{k}={v}")
    body.append("")  # trailing newline
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(body), encoding="utf-8")


def _ensure_env(rotate: bool) -> dict[str, str]:
    existing = _read_env(ENV_FILE)
    needed = {
        "PPS_SECRET_KEY": lambda: _gen(48),
        "PPS_API_KEY": lambda: _gen_api_key("dev"),
        "POSTGRES_PASSWORD": lambda: _gen(24),
        "REDIS_PASSWORD": lambda: _gen(24),
    }
    constants = {
        "PPS_ENV": "development",
        "PPS_LOG_LEVEL": "INFO",
        "S3_BUCKET": "pps-dev",
        "S3_ENDPOINT_URL": "http://minio:9000",
        "S3_ACCESS_KEY": "minioadmin",
        "S3_SECRET_KEY": "minioadmin",
        "S3_REGION": "auto",
        "PPS_REQUIRE_API_KEY": "false",  # keep frictionless in dev
        "NEXT_PUBLIC_BRAND_NAME": "Pro Photo Studio",
        "NEXT_PUBLIC_BRAND_TAGLINE": "Real-estate photo enhancement, automated.",
    }

    final = dict(existing)
    for k, factory in needed.items():
        if rotate or not final.get(k):
            final[k] = factory()
    for k, v in constants.items():
        final.setdefault(k, v)

    _write_env(
        ENV_FILE,
        final,
        "Pro Photo Studio — local development environment.\nDo not commit this file.",
    )
    print(f"[bootstrap] wrote {ENV_FILE.relative_to(REPO_ROOT)}")

    web_env = {
        "PPS_API_URL": "http://localhost:8000",
        "PPS_API_KEY": final["PPS_API_KEY"],
        "NEXT_PUBLIC_BRAND_NAME": final["NEXT_PUBLIC_BRAND_NAME"],
        "NEXT_PUBLIC_BRAND_TAGLINE": final["NEXT_PUBLIC_BRAND_TAGLINE"],
        "NEXT_PUBLIC_SITE_URL": "http://localhost:3001",
    }
    _write_env(
        WEB_ENV_FILE,
        web_env,
        "Pro Photo Studio web portal — local environment.",
    )
    print(f"[bootstrap] wrote {WEB_ENV_FILE.relative_to(REPO_ROOT)}")
    return final


def _compose(*args: str, env: dict[str, str] | None = None) -> int:
    docker = _need("docker")
    return subprocess.call(
        [docker, "compose", "-f", str(COMPOSE_FILE), *args],
        cwd=REPO_ROOT,
        env={**os.environ, **(env or {})},
    )


def _wait_for(url: str, *, timeout: float = 90.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as resp:  # noqa: S310 — local URL
                if 200 <= resp.status < 300:
                    return True
        except (urllib.error.URLError, ConnectionError, TimeoutError):
            pass
        time.sleep(2)
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap the local development stack.")
    parser.add_argument(
        "--rotate-keys",
        action="store_true",
        help="Force-regenerate secrets (api key, postgres password, etc).",
    )
    parser.add_argument(
        "--no-up",
        action="store_true",
        help="Generate .env files but skip 'docker compose up'.",
    )
    args = parser.parse_args()

    if not COMPOSE_FILE.is_file():
        sys.exit(f"error: missing {COMPOSE_FILE}; run from the repo root.")
    _check_docker_compose()
    env_values = _ensure_env(rotate=args.rotate_keys)

    if args.no_up:
        print("[bootstrap] skipping 'docker compose up' (--no-up)")
        return 0

    print("[bootstrap] starting docker compose…")
    rc = _compose("up", "-d", "--build", env=env_values)
    if rc != 0:
        return rc

    print("[bootstrap] waiting for API to become healthy…")
    if _wait_for("http://localhost:8000/health"):
        print("  ✓ http://localhost:8000/health")
    else:
        print("  ✗ /health did not come up — check 'docker compose logs api'")
        return 1

    print("[bootstrap] waiting for web portal…")
    if _wait_for("http://localhost:3001/", timeout=60):
        print("  ✓ http://localhost:3001/")
    else:
        print("  ✗ web did not come up — check 'docker compose logs web'")

    print()
    print("──────────────────────────────────────────────────────────────")
    print(" Pro Photo Studio is up.")
    print()
    print("  Web portal       http://localhost:3001")
    print("  API + Swagger    http://localhost:8000/docs")
    print("  MinIO console    http://localhost:9001  (minioadmin / minioadmin)")
    print()
    print("  Dev API key (X-API-Key, only needed if PPS_REQUIRE_API_KEY=true):")
    print("    " + env_values.get("PPS_API_KEY", "<missing>"))
    print()
    print("  Stop:    docker compose -f deploy/docker-compose.dev.yml down")
    print("  Logs:    docker compose -f deploy/docker-compose.dev.yml logs -f")
    print("──────────────────────────────────────────────────────────────")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
