"""Discover new public OSS repos around photo-enhancement / RAW / SR.

Runs in `.github/workflows/weekly-discovery.yml`. Outputs a Markdown report
(default ``discovery_report.md``) that the workflow attaches to a PR. Doesn't
modify the repo — humans review the report and decide what to integrate.

Sources:
  * GitHub: ``GET /search/repositories?q=...`` filtered to last 7 days.
  * Hugging Face: ``HfApi.list_models / list_datasets`` filtered by tag.

Auth:
  * GitHub: ``GH_TOKEN`` (PAT, ``public_repo`` scope is enough).
  * Hugging Face: ``HF_TOKEN`` (read scope; optional — anonymous works for
    most queries with reduced rate limit).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger("pps.discover")

GITHUB_API = "https://api.github.com"
TOPICS_QUERY = " ".join(
    [
        "topic:photo-enhancement",
        "topic:super-resolution",
        "topic:raw-processing",
        "topic:image-enhancement",
        "topic:hdr",
    ]
)


@dataclass
class Hit:
    source: str  # "github" | "huggingface"
    name: str
    url: str
    description: str = ""
    stars: int | None = None
    pushed_at: str | None = None
    tags: list[str] = field(default_factory=list)


def search_github(token: str | None, *, since_days: int = 7, max_results: int = 30) -> list[Hit]:
    since = (dt.datetime.utcnow() - dt.timedelta(days=since_days)).date().isoformat()
    q = f"{TOPICS_QUERY} pushed:>={since}"
    url = f"{GITHUB_API}/search/repositories?{urllib.parse.urlencode({'q': q, 'sort': 'updated', 'per_page': max_results})}"
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        log.warning("GitHub HTTP %s: %s", e.code, e.read()[:200])
        return []
    except urllib.error.URLError as e:
        log.warning("GitHub URL error: %s", e)
        return []
    return [
        Hit(
            source="github",
            name=item["full_name"],
            url=item["html_url"],
            description=item.get("description") or "",
            stars=item.get("stargazers_count"),
            pushed_at=item.get("pushed_at"),
            tags=item.get("topics", []),
        )
        for item in payload.get("items", [])[:max_results]
    ]


def search_hf(token: str | None, *, max_results: int = 20) -> list[Hit]:
    try:
        from huggingface_hub import HfApi
    except ImportError:
        log.warning("huggingface-hub not installed — skipping HF source")
        return []
    api = HfApi(token=token)
    out: list[Hit] = []
    try:
        models = api.list_models(
            filter=["image-to-image"], sort="lastModified", direction=-1, limit=max_results
        )
    except Exception as e:
        log.warning("HF list_models failed: %s", e)
        return []
    for m in models:
        out.append(
            Hit(
                source="huggingface",
                name=m.id,
                url=f"https://huggingface.co/{m.id}",
                description=getattr(m, "description", "") or "",
                pushed_at=str(getattr(m, "last_modified", "") or ""),
                tags=list(getattr(m, "tags", []) or []),
            )
        )
    return out


def render_report(hits: list[Hit]) -> str:
    today = dt.date.today().isoformat()
    lines = [
        f"# Weekly OSS discovery — {today}",
        "",
        f"_Auto-generated by `scripts/discover_repos.py` ({len(hits)} candidates)._",
        "",
        "Review each entry; merge what's useful into deps or `docs/ROADMAP.md`.",
        "",
    ]
    for src in ("github", "huggingface"):
        sub = [h for h in hits if h.source == src]
        if not sub:
            continue
        lines.append(f"## {src.title()} ({len(sub)})")
        lines.append("")
        lines.append("| Repo | Stars | Updated | Topics | Description |")
        lines.append("|---|---|---|---|---|")
        for h in sub:
            stars = "" if h.stars is None else f"{h.stars}⭐"
            tags = ", ".join(h.tags[:5]) if h.tags else ""
            desc = (h.description or "").replace("|", "\\|").replace("\n", " ")[:200]
            lines.append(f"| [{h.name}]({h.url}) | {stars} | {h.pushed_at or ''} | {tags} | {desc} |")
        lines.append("")
    if not hits:
        lines.append("_(no new candidates this week)_")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=Path("discovery_report.md"))
    parser.add_argument("--since-days", type=int, default=7)
    parser.add_argument("--max-results", type=int, default=30)
    parser.add_argument("--dry-run", action="store_true",
                        help="Use a fixture instead of hitting the network")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    if args.dry_run:
        hits = [
            Hit(source="github", name="example/super-resolution", url="https://github.com/example/super-resolution",
                description="Toy dry-run hit", stars=42, pushed_at="2026-05-01T00:00:00Z",
                tags=["super-resolution", "raw-processing"]),
            Hit(source="huggingface", name="example/raw-enhancer", url="https://huggingface.co/example/raw-enhancer",
                description="Toy HF hit", tags=["image-to-image"]),
        ]
    else:
        gh_token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
        hf_token = os.environ.get("HF_TOKEN")
        hits = (
            search_github(gh_token, since_days=args.since_days, max_results=args.max_results)
            + search_hf(hf_token, max_results=20)
        )

    args.out.write_text(render_report(hits), encoding="utf-8")
    print(f"wrote {args.out} with {len(hits)} hits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
