"""Pipeline contract — frozen dataclasses + Protocol shared by stages.

This module is the *single source of truth* for the data structures every
stage and every API endpoint speaks. Keep it minimal and stable: any change
here ripples through the entire codebase.

Design principles
-----------------
1. **Frozen dataclasses**: Job, Stage, Report are values, not handles. They
   serialise cleanly to JSON for the public API and to dicts for logging.
2. **One protocol for stages**: ``Stage`` is a callable that accepts an image
   plus a ``StageContext`` and returns ``(image, StageReport)``. No exceptions
   for skip/error: stages emit a report with ``skipped=True`` or
   ``error=...`` and the runner decides what to do.
3. **Deterministic seed**: jobs carry an optional ``seed: int``. When set,
   the runner derives a per-stage seed via ``seed_for_stage(seed, name)`` so
   that re-running the same job on the same input produces byte-identical
   output.
4. **Forward-compatible options**: stage parameters live in
   ``Job.params: Mapping[str, Mapping[str, Any]]`` keyed by stage name. New
   stages do not require modifying ``Job``.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

import numpy as np

__all__ = [
    "Job",
    "Report",
    "Severity",
    "Stage",
    "StageContext",
    "StageReport",
    "seed_for_stage",
]

Severity = str  # one of: "info", "warn", "error", "fatal" — kept loose for forward compat


@dataclass(frozen=True, slots=True)
class Job:
    """A unit of work submitted to the pipeline.

    Attributes:
        job_id:
            Unique identifier (UUID4 hex). Generated by the API layer; tests
            may pass a fixed string.
        stages:
            Ordered tuple of stage names to run. The runner looks each name
            up in its registry and skips unknown names with a warning.
        params:
            Per-stage parameters. ``params["sky_replace"]`` becomes the
            ``params`` argument to the ``sky_replace`` stage.
        seed:
            Deterministic seed. ``None`` = non-deterministic. The runner
            propagates ``seed_for_stage(seed, stage.name)`` into the
            ``StageContext``.
        metadata:
            Free-form key-value bag for traceability (user, ip, source).
            Never used to control stage behavior.
    """

    job_id: str
    stages: tuple[str, ...]
    params: Mapping[str, Mapping[str, Any]] = field(default_factory=dict)
    seed: int | None = None
    metadata: Mapping[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class StageContext:
    """Per-stage runtime context passed to ``Stage.__call__``.

    Stages MUST treat this as read-only. The runner builds a fresh context
    for each stage so mutations would not propagate anyway, but treating it
    as immutable keeps stage code testable in isolation.
    """

    job: Job
    stage_name: str
    stage_seed: int | None
    """Seed derived from ``job.seed`` and ``stage_name``. ``None`` if the job is
    non-deterministic."""

    params: Mapping[str, Any]
    """Parameters specific to this stage, taken from ``job.params[stage_name]``.

    Empty mapping if the job did not supply any."""


@dataclass(frozen=True, slots=True)
class StageReport:
    """Outcome of a single stage execution.

    Attributes:
        name: Stage name (echoed for log/aggregation).
        applied: True if the stage produced a meaningful change. False when
            the stage detected the input did not warrant the operation
            (e.g. perspective correction with too few vertical lines).
        skipped: True if the stage was requested but had to be skipped.
            ``reason`` should explain why.
        error: Exception representation if the stage raised. The runner
            captures it instead of propagating, so a downstream stage can
            still attempt its work.
        duration_ms: Wall-clock execution time in milliseconds.
        warnings: Soft issues the stage wants to surface (e.g. low blur
            score). Each warning is ``(severity, message)``.
        metrics: Numeric outputs (PSNR, mask coverage, etc.). Stage-specific
            keys.
        reason: Human-readable explanation for skip / soft-failure cases.
    """

    name: str
    applied: bool = False
    skipped: bool = False
    error: str | None = None
    duration_ms: float = 0.0
    warnings: tuple[tuple[Severity, str], ...] = ()
    metrics: Mapping[str, float] = field(default_factory=dict)
    reason: str = ""


@dataclass(frozen=True, slots=True)
class Report:
    """Job-level aggregation of every stage's outcome."""

    job_id: str
    stages: tuple[StageReport, ...]
    duration_ms: float
    halted: bool = False
    """True if the runner stopped before processing all requested stages —
    typically because a stage raised an unrecoverable error and the runner
    was configured with ``halt_on_error=True``."""

    @property
    def applied_stages(self) -> tuple[str, ...]:
        return tuple(s.name for s in self.stages if s.applied)

    @property
    def skipped_stages(self) -> tuple[str, ...]:
        return tuple(s.name for s in self.stages if s.skipped)

    @property
    def errored_stages(self) -> tuple[str, ...]:
        return tuple(s.name for s in self.stages if s.error)


@runtime_checkable
class Stage(Protocol):
    """Protocol every pipeline stage must satisfy.

    A stage is a callable taking ``(image_bgr_uint8, ctx)`` and returning
    ``(image_bgr_uint8, StageReport)``. Stages MUST NOT raise on bad input
    — they emit a ``StageReport(skipped=True, reason=...)`` instead. If a
    stage *does* raise, the runner catches the exception and attaches it to
    the report.

    Stages should be pure functions of their input (image + ctx). They may
    cache loaded resources (e.g. ML weights) but must not retain mutable
    state across calls that would affect determinism for the same seed.
    """

    name: str

    def __call__(self, image: np.ndarray, ctx: StageContext) -> tuple[np.ndarray, StageReport]: ...


def seed_for_stage(job_seed: int | None, stage_name: str) -> int | None:
    """Derive a deterministic per-stage seed from ``(job_seed, stage_name)``.

    Returns ``None`` if ``job_seed`` is ``None`` (non-deterministic job).
    Otherwise returns a uint32 derived from a stable hash so the same job
    and stage always produce the same per-stage seed across machines.
    """
    if job_seed is None:
        return None
    digest = hashlib.blake2b(f"{job_seed}:{stage_name}".encode(), digest_size=4).digest()
    return int.from_bytes(digest, byteorder="big")
